version: '3.1'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports: 
      - "5672:5672"
      - "15672:15672"
    networks:
      - network_default

networks:
  network_default:
    driver: bridge
